# Generated by Django 2.2.4 on 2019-10-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191005_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
