# Generated by Django 2.2.4 on 2019-10-06 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='piblished',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación'),
        ),
    ]
